### ISSUE TITLE
How to train for different dataset (4 classes)

### ISSUE THREAD

**Issue by murari023** [WenchaoliuMUC/Detection-of-Multiclass-Objects-in-Optical-Remote-Sensing-Images#1]
Hi,
I am trying to train this model for my 4-class dataset. I have made all the necessary changes in the cfg files and other places. Since, it is loading a pretrained weight for training, how to make it run for 4-class dataset?

**Comment by murari023** [comment]
I am getting the following error.

(tensorflow_gpuenv) ➜  Detection-of-Multiclass-Objects-in-Optical-Remote-Sensing-Images-master python train.py cfg/dota.data cfg/orn_4_dota.cfg backup/000057.weights  
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    train(epoch)
  File "train.py", line 123, in train
    loss = region_loss(output, target, batch_idx)
  File "/home/cvprlab0/anaconda3/envs/tensorflow_gpuenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "region_loss.py", line 144, in region_loss.RegionLoss.forward
  File "region_loss.py", line 35, in region_loss.build_targets
RuntimeError: The shape of the mask [7220] at index 0 does not match the shape of the indexed tensor [5, 38, 38] at index 0

**Comment by murari023** [comment]
The author updated the required region_loss.py function

**Comment by Baby47** [comment]
Hi, I wonder if you have successfully trained your model. I find there is no file orn.py as is imported in deform_darknet.py.  @murari023 @WenchaoliuMUC 
Thanks
