### ISSUE TITLE
能预测旋转矩形框么？比如像R2CNN那样的

### ISSUE THREAD

**Issue by clw5180** [WenchaoliuMUC/Detection-of-Multiclass-Objects-in-Optical-Remote-Sensing-Images#2]
你的mAP能达到多少？我用R2CNN只能达到0.1多一点....对于你的这个repo，我想问下比如有些small-vehicle是45°放置的，如果用水平框标出来，IOU是不是达不到要求？

**Comment by clw5180** [comment]
不好意思，没注意到你是Task2

**Comment by Baby47** [comment]
Hi, Have you tried this repo on your own dataset in horizontal bounding box detection tasks, @clw5180
